### ISSUE TITLE
Event tracking - Increase count

### ISSUE THREAD

**Issue by LukeHankey** [LukeHankey/DSF-Event-Tracker#4]
This will be an opt-in feature whereby calls that are sent to Discord from a client can have that event recorded onto a profile which the DSF Discord Bot tracks for scouter membership. 

To ensure that all users receive credit for the call, all clients where the app attempts to send the call via the webhook will receive credit as long as the event is picked up by the client within a couple of seconds.

- [x] Create API endpoint to add count to a user profile in the Discord Bots' database. 
- [x] Create a user profile if one doesn't exist.
- [x] Decide on whether the scouter/verified limit should be changed or should calls made through this app be added to a separate count?
- [x] Modify the call duplication in the server to check for incoming repeat calls within some short timeframe (1-3 seconds) and give credit for the call.
